### ISSUE TITLE
Cannot transfer Silk Touch to diamond pick

### ISSUE THREAD

**Issue by Knito58** [Cheaterpaul/EnchantmentMachine#8] opened 2021-05-10 13:54 UTC
I did enchant (vanilla) and disenchant (your mod) my golden pick about 20 times until a "silk touch" was found. This was then disenchanted likewise.

Now there's the big moment when the enchantment would make its way to my shiny new diamond pick.
It is popped into the enchanter, silk touch and many other pick-enchants are shown.

Clicking on silk touch or on any other just gives a click sound. The pick gets not enchanted. The green arrow says "enchant using 4 levels". Click. Nothing happens. Nothing is consumed, nothing is destroyed.

Trying to enchant other things like a diamond helmet (using up 4 levels also) just worked nicely as expected.

Did I miss something?

**Comment by Knito58** [comment] 2021-05-10 14:48
After restarting Minecraft it did not work, either. But putting "efficiency III" on the pick worked.
And after this putting "silk touch" on it worked, too.
Now - my problem solved and I know how to make this in the next world. But there is still a question:

Why?

**Comment by Cheaterpaul** [comment] 2021-05-10 15:57
Is this reproducible? And did you modify config values?

Atm i am not sure what could cause this, my first thought was a server/client data mismatch, but since still did not work after a restart as well that should not be the case. The other thing i can think of is a bug in the server side code.

**Comment by Knito58** [comment] 2021-05-10 16:00
Config was not altered by me. I don't know whether it would have worked with first enchanting st else the first time. But it was stuck after second clean start.

**Comment by Knito58** [comment] 2021-05-10 16:01
It feels like a rule that forbids the enchantment in some circumstances.

**Comment by Cheaterpaul** [comment] 2021-05-10 16:02
do you still have the log files for the moment of the enchanting?

**Comment by Knito58** [comment] 2021-05-10 16:06
Have a "latest.log" with no reference to enchantementmachine in it but the two former logfiles should have st in them.

**Comment by Cheaterpaul** [comment] 2021-05-10 16:08
yes, that would probably help if you can attach them

**Comment by Knito58** [comment] 2021-05-10 16:09
[2021-05-10-3.log.gz](https://github.com/Cheaterpaul/EnchantmentMachine/files/6453466/2021-05-10-3.log.gz)
[2021-05-10-2.log.gz](https://github.com/Cheaterpaul/EnchantmentMachine/files/6453467/2021-05-10-2.log.gz)

**Comment by Knito58** [comment] 2021-05-10 16:09
[latest.log](https://github.com/Cheaterpaul/EnchantmentMachine/files/6453476/latest.log)

**Comment by Knito58** [comment] 2021-05-10 16:09
Just to be complete....

**Comment by Cheaterpaul** [comment] 2021-05-10 16:48
unfortunately i couldn't find any relevant information.

i added a few logging lines.  Could you test the procedure again with the following test version and send me the debug log afterwards?
[testversion.zip](https://github.com/Cheaterpaul/EnchantmentMachine/files/6453715/testversion.zip)

**Comment by Knito58** [comment] 2021-05-10 17:38
Silly question: Which folder is it where the debug.log is in?
[latest.log](https://github.com/Cheaterpaul/EnchantmentMachine/files/6453949/latest.log)
Disenchanted the pick. Clicked 4 times on the green arrow of "silk touch" (not works) and ended game.

**Comment by Cheaterpaul** [comment] 2021-05-10 17:45
That should be in the same folder as the latest.log

**Comment by Knito58** [comment] 2021-05-10 17:45
This should be the "logs" folder. But there's 

... nothing ...

**Comment by Knito58** [comment] 2021-05-10 17:47
You can see in the latest.log a warning that your dev version is installed. Would send debug.log if it was there. Is it only written when I set some vars in Forge to debug mode?

**Comment by Cheaterpaul** [comment] 2021-05-10 18:56
Couldn't find out myself so here a version where the latest log should suffice. 
[testversion.zip](https://github.com/Cheaterpaul/EnchantmentMachine/files/6454371/testversion.zip)

**Comment by Knito58** [comment] 2021-05-10 18:59
... starting up

**Comment by Knito58** [comment] 2021-05-10 19:03
[latest.log](https://github.com/Cheaterpaul/EnchantmentMachine/files/6454403/latest.log)
Disenchanted the pick again and tried to enchant it with silk touch.
Levels on player = 7 (after all that testing it went down)
But that should have worked as it really strips 4 levels.

**Comment by Pocketsnb** [comment] 2021-05-10 22:37
I'm getting similar behavior. Sometimes I can place enchants on a book, other times the UI doesn't allow update. Unfortunately, do not have time at the moment to do thorough testing.
Like, I can place a book in it, enchant it a few times, but then it locks up. Put in a different book and it won't let me enchant it. Place in a helmet and I can place an enchantment on it. Place the book back in and I still can't enchant it.

**Comment by Cheaterpaul** [comment] 2021-05-12 17:04
I looked again and i still have no clue what is going on.

First of all are you using a modpack where i can test it myself?

Otherwise i have 2 options left:
1. [testversion.zip](https://github.com/Cheaterpaul/EnchantmentMachine/files/6467849/testversion.zip) i created another testversion with detailed log informations 
2. test with version 1.0.0 https://www.curseforge.com/minecraft/mc-mods/enchantment-machine/files/3241809

**Comment by Knito58** [comment] 2021-05-14 04:24
Modpack: I made one which is not jet visible when searching: A ticket is on its way.
https://www.curseforge.com/minecraft/modpacks/konitorpack
I will install the new test version.
I have the same issues as @Pocketsnb when moving Enchantments to a book.
Gonna install the new testversion and send latest.log.

**Comment by Knito58** [comment] 2021-05-14 04:36
[debug.log](https://github.com/Cheaterpaul/EnchantmentMachine/files/6476530/debug.log)
[latest.log](https://github.com/Cheaterpaul/EnchantmentMachine/files/6476531/latest.log)
This time after disenchanting the silk pick it worked.
I added also unbreaking III -> worked.
Then efficiency III -> stuck again.
After visiting the dragon my xp level was 69, should be enough for them 3 enchantments.

**Comment by Knito58** [comment] 2021-05-14 05:08
After restarting game the silk touch pick was lost - i had left it in the enchanter.

**Comment by Cheaterpaul** [comment] 2021-05-14 12:49
using KonitorPack 1.16.5-0.0.3:
(after replacing charm 2.2.2 with 2.3.2 since otherwise minecraft couldn't start)
Unfortunately i could not reproduce the enchanting error.

But while looking at your logs i could not find any traces of loading the mod (debug.log) or logging (latest.log). I don't want to sound rude, but are you sure that you are using the test version? The mod description int the mod list should look like this
![2021-05-14_14 46 55](https://user-images.githubusercontent.com/17816456/118272674-425dd480-b4c3-11eb-8e7c-4a85095aa44b.png)

> After restarting game the silk touch pick was lost - i had left it in the enchanter.

will be fixed


But thanks for debugging this with me and wasting your levels

**Comment by Knito58** [comment] 2021-05-14 15:15
![grafik](https://user-images.githubusercontent.com/2604989/118290420-b5bd1180-b4d6-11eb-9376-2dc2eb74eab7.png)
Sorry you're the first to test the uploaded KPack Version, I wanted to do this with my server as it turns out that what I have in my CurseForge Install Folder is not 1:1 what CurseForge believes it would "export". I have to clean out said export by hand. But what is on my machine that runs. Sorry for that. In the screenshot you see my modlist (catalogue from Mr Crayfish) and your Mod is inside. Also I uploaded a debug.log, which did not show up before the last 1.0.2 testversion.

I do not want to nag you. I want to help.

The logs were copied after shutting down after multiple unsuccessful attempts to put level III efficiency on my silk pick. In this attempt the silk touch enchantment worked, then the  unbreaking worked and then it got stuck with efficiency again.

Player XP level was over 60 after returning from first END visit in this world. The arrow for "efficiency" was green, indicating it would work. There were some other arrows in red indicating it would not work.

**Comment by Knito58** [comment] 2021-05-14 15:28
Curseforge Helpdesk Ticket https://support.curseforge.com/en/support/tickets/91207
The issue is that Serverminer needs to find the ModPack in the CurseForge List. But it does not show up, even in CurseForge's own list. I cannot issue a link to the modpack. So it is still untested. Again sorry.

**Comment by Pocketsnb** [comment] 2021-05-14 17:26
Logs And CurseForge modpack export if that helps.
[debug.log](https://github.com/Cheaterpaul/EnchantmentMachine/files/6480252/debug.log)
[latest.log](https://github.com/Cheaterpaul/EnchantmentMachine/files/6480253/latest.log)

[Heavy-Tech World.zip](https://github.com/Cheaterpaul/EnchantmentMachine/files/6480262/Heavy-Tech.World.zip)

I don't see anything in the log files that indicates why it stops working, just that it was successful the last time it could enchant something.

**Comment by Cheaterpaul** [comment] 2021-05-18 13:58
Thanks Pocketsnb,

at least it logs something.
is this only the server log file or the client log files?

Since i still couldn't reproduce it i have a last try at logging all possible relevant information.
[final.zip](https://github.com/Cheaterpaul/EnchantmentMachine/files/6501846/final.zip) (i also changed something; maybe is works)
(Please make sure to send the the server & client logs if playing on a server.)

**Comment by Pocketsnb** [comment] 2021-05-18 15:52
I think I've found the issue. When using the scroll bar on the side, it locks clicking of the buttons.
I've uploaded a video recording the enchanting process.
[Enchantment Machine Debugging](https://youtu.be/Hlxclvhmc3A)
[debug (server).log](https://github.com/Cheaterpaul/EnchantmentMachine/files/6502633/debug.server.log)
[latest (server).log](https://github.com/Cheaterpaul/EnchantmentMachine/files/6502634/latest.server.log)
[latest (client).log](https://github.com/Cheaterpaul/EnchantmentMachine/files/6502642/latest.client.log)

**Comment by Cheaterpaul** [comment] 2021-05-18 16:51
Nice thanks for the video, no i can reproduce this

**Comment by Cheaterpaul** [comment] 2021-05-18 17:08
yes found the error.

@Knito58  can you test if [fix.zip](https://github.com/Cheaterpaul/EnchantmentMachine/files/6503063/fix.zip) solves the problem for you as well?

**Comment by Pocketsnb** [comment] 2021-05-18 23:58
Working for me!

**Comment by Cheaterpaul** [comment] 2021-05-26 14:23
As i assume this has fixed all issues here:  https://www.curseforge.com/minecraft/mc-mods/enchantment-machine/files/3325606

**Closed as completed by Cheaterpaul** 2021-05-26 14:23 UTC
Labels: bug

**Comment by Knito58** [comment] 2021-05-27 20:09
Sorry, had some days with my grandchildren and forgot about this issue.
